# Generated by Django 3.0.5 on 2020-05-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0016_variety_updated_by'),
        ('auth', '0011_update_proxy_permissions'),
        ('usrmgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ManyToManyField(null=True, to='seed.Country')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
            ],
        ),
    ]
