# Generated by Django 2.2 on 2020-04-17 11:37

from django.db import migrations, models
import django.db.models.deletion
import seed.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_field', models.CharField(choices=[('s', 'seeds'), ('f2', 'field2'), ('f3', 'field3')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CropFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('business_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.BusinessDivision')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('business_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.BusinessDivision')),
            ],
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('common_name', models.CharField(blank=True, max_length=50, null=True)),
                ('latin_name', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='seed/repo/speices/image/')),
                ('seed_count_per_gramme_min_interval', models.IntegerField(blank=True, null=True)),
                ('seed_count_per_gramme_max_interval', models.IntegerField(blank=True, null=True)),
                ('germination_lasts_year_min_interval', models.IntegerField(blank=True, null=True)),
                ('germination_lasts_year_max_interval', models.IntegerField(blank=True, null=True)),
                ('sow_type', models.CharField(blank=True, choices=[('d', 'DIRECT SOWING'), ('t', 'TRANSPLANT'), ('b', 'Both')], default='b', max_length=1, null=True)),
                ('direct_sowing_type', models.CharField(blank=True, choices=[('h', 'By Hand'), ('m', 'Machine')], default='h', max_length=1, null=True)),
                ('hand_type', models.CharField(blank=True, choices=[('s', 'seed by seed'), ('b', 'broadcasted')], default='s', max_length=1, null=True)),
                ('sow_KG_HA_direct_min_interval', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sow_KG_HA_direct_max_interval', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sow_KG_HA_transplant_min_interval', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sow_KG_HA_transplant_max_interval', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depth_type', models.CharField(blank=True, choices=[('d', 'DIRECT SOWING'), ('t', 'TRANSPLANT'), ('b', 'Both')], default='d', max_length=1, null=True)),
                ('depth_min_interval', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depth_max_interval', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance_CM_row_to_row_min_interval', models.IntegerField(blank=True, null=True)),
                ('distance_CM_row_to_row_max_interval', models.IntegerField(blank=True, null=True)),
                ('distance_CM_plant_to_plant_min_interval', models.IntegerField(blank=True, null=True)),
                ('distance_CM_plant_to_plant_max_interval', models.IntegerField(blank=True, null=True)),
                ('sprouting_time_days_min_interval', models.IntegerField(blank=True, null=True)),
                ('sprouting_time_days_max_interval', models.IntegerField(blank=True, null=True)),
                ('crop_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.CropFamily')),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('serial_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('variety_seed_type', models.CharField(choices=[('o', 'Open Pollinated'), ('h', 'Hybrid')], max_length=2)),
                ('global_name', models.CharField(blank=True, max_length=50, null=True)),
                ('variety_supplier_name', models.CharField(max_length=50)),
                ('variety_supplier_id', models.CharField(blank=True, max_length=50, null=True, validators=[seed.validators.space_prohibited_validator])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='seed/repo/variety/image')),
                ('photo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('photo_legend', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.CropFamily')),
                ('global_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.GlobalCrop')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.ProductType')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.Species')),
                ('supplier_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='VarietyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VarietySupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='seed/repo/supplier/image')),
                ('document', models.FileField(blank=True, null=True, upload_to='seed/repo/supplier/document')),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('variety', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seed.Variety')),
            ],
        ),
        migrations.CreateModel(
            name='VarietyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='seed/repo/variety/image')),
                ('legend', models.CharField(blank=True, max_length=200, null=True)),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.Variety')),
            ],
        ),
        migrations.CreateModel(
            name='VarietyFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.VarietyField')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.Variety')),
            ],
        ),
        migrations.CreateModel(
            name='VarietyBaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(blank=True, choices=[('f', 'FRESH'), ('p', 'PROCESSING'), ('fp', 'FRESH/PROCESSING')], max_length=2, null=True)),
                ('ecology', models.CharField(blank=True, choices=[('AG', 'ACTIVE GREENHOUSE'), ('OF', 'OPEN FIELD'), ('OC', 'OUTDOORS, PROTECTED CULTURE'), ('PG', 'PASSIVE GREENHOUSE'), ('TE', 'TEMPERATE'), ('TR', 'TROPICAL')], max_length=2, null=True)),
                ('production_cycle', models.CharField(blank=True, choices=[('1', 'ACTIVE GREENHOUSE'), ('2', 'AUTUMN'), ('3', 'COOL'), ('4', 'COOL TO WARM'), ('5', 'EARLY'), ('6', 'FIRST EARLY'), ('7', 'LATE'), ('8', 'MAIN'), ('9', 'MEDIUM'), ('10', 'SECOND EARLY'), ('11', 'SPRING'), ('12', 'SPRING/AUTUMN'), ('13', 'SUMMER'), ('14', 'TROPICAL'), ('15', 'VERY LATE'), ('16', 'WARM'), ('17', 'WARM TO COOL'), ('18', 'WARM TO COOL TO WARM'), ('19', 'WINTER')], max_length=2, null=True)),
                ('color', models.CharField(blank=True, choices=[('1', 'BICOLOR'), ('2', 'BLACK'), ('3', 'DARK GREEN'), ('4', 'GREEN'), ('5', 'GREY'), ('6', 'LIGHT GREEN'), ('7', 'MEDIUM GREEN'), ('8', 'ORANGE'), ('9', 'PINK'), ('10', 'PURPLE'), ('11', 'RED'), ('12', 'WAX'), ('13', 'WHITE'), ('14', 'YELLOW')], max_length=2, null=True)),
                ('technical_description', models.CharField(blank=True, max_length=300, null=True)),
                ('unique_selling_points_and_commercial_positioning', models.CharField(blank=True, max_length=100, null=True)),
                ('competition', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='seed/repo/Bancella/image')),
                ('document', models.FileField(blank=True, null=True, upload_to='seed/repo/Bancella/document')),
                ('variety', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seed.Variety')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='seed/gallery')),
                ('legend', models.CharField(blank=True, max_length=200, null=True)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.Species')),
            ],
        ),
        migrations.AddField(
            model_name='producttype',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.Species'),
        ),
        migrations.CreateModel(
            name='ProductLifeCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_name', models.CharField(max_length=50)),
                ('other_global_name', models.CharField(blank=True, max_length=50, null=True)),
                ('global_plc', models.CharField(choices=[('0', 'Recorded'), ('1', 'Screening'), ('2', 'Development year 1'), ('3', 'Development year 2'), ('4', 'Pre-commercial'), ('5', 'Phase in'), ('6', 'Growth'), ('7', 'Cash'), ('8', 'Sell-out'), ('9', 'Phase out'), ('10', 'Obsolete')], max_length=2)),
                ('global_plc_date', models.DateField(blank=True, null=True)),
                ('global_plc_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.Variety')),
            ],
            options={
                'ordering': ['global_plc_date'],
            },
        ),
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph', models.ImageField(blank=True, null=True, upload_to='')),
                ('model2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.Model2')),
            ],
        ),
        migrations.AddField(
            model_name='cropfamily',
            name='global_crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.GlobalCrop'),
        ),
        migrations.CreateModel(
            name='CountryPLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(choices=[('0', 'Recorded'), ('1', 'Screening'), ('2', 'Development year 1'), ('3', 'Development year 2'), ('4', 'Pre-commercial'), ('5', 'Phase in'), ('6', 'Growth'), ('7', 'Cash'), ('8', 'Sell-out'), ('9', 'Phase out'), ('10', 'Obsolete')], max_length=2)),
                ('local_plc_date', models.DateField()),
                ('trial_and_development_results', models.CharField(blank=True, max_length=200, null=True)),
                ('go_to_market_approach', models.CharField(blank=True, max_length=200, null=True)),
                ('local_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('local_picture', models.FileField(upload_to='seed/repo/country_plc/document')),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.Contact')),
                ('global_plc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.ProductLifeCycle')),
                ('person_in_charge_of_development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.Person')),
            ],
        ),
    ]
