# Generated by Django 2.2 on 2020-02-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='seed/gallery')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.Family')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.Species')),
            ],
        ),
        migrations.CreateModel(
            name='VarietyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VarietyFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.VarietyField')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.Variety')),
            ],
        ),
        migrations.CreateModel(
            name='FamilySpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_count_per_gramme_min_interval', models.IntegerField(blank=True, null=True)),
                ('seed_count_per_gramme_max_interval', models.IntegerField(blank=True, null=True)),
                ('germ_lasts_year_min_interval', models.IntegerField(blank=True, null=True)),
                ('germ_lasts_year_max_interval', models.IntegerField(blank=True, null=True)),
                ('sow_type1', models.CharField(blank=True, choices=[('d', 'DIRECT SOWING'), ('t', 'TRANSPLANT'), ('m', 'MACHINE SOWING'), ('h', 'BY HAND')], default='d', max_length=1)),
                ('sow_KG_HA_min_interval1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sow_KG_HA_max_interval1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sow_type2', models.CharField(blank=True, choices=[('d', 'DIRECT SOWING'), ('t', 'TRANSPLANT'), ('m', 'MACHINE SOWING'), ('h', 'BY HAND')], default='t', max_length=1)),
                ('sow_KG_HA_min_interval2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sow_KG_HA_max_interval2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('depth_type', models.CharField(blank=True, choices=[('s', 'SOWING CM'), ('t', 'TRANSPLANT')], default='s', max_length=1)),
                ('depth_min_interval', models.IntegerField(blank=True, null=True)),
                ('depth_max_interval', models.IntegerField(blank=True, null=True)),
                ('distance_CM_row_to_row_min_interval', models.IntegerField(blank=True, null=True)),
                ('distance_CM_row_to_row_max_interval', models.IntegerField(blank=True, null=True)),
                ('distance_CM_plant_to_plant_min_interval', models.IntegerField(blank=True, null=True)),
                ('distance_CM_plant_to_plant_max_interval', models.IntegerField(blank=True, null=True)),
                ('sprouting_time_days_min_interval', models.IntegerField(blank=True, null=True)),
                ('sprouting_time_days_max_interval', models.IntegerField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.Family')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seed.Species'),
        ),
    ]
