# Generated by Django 3.0.5 on 2020-04-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='variety_supplier_name',
            field=models.CharField(max_length=70),
        ),
    ]
