# Generated by Django 2.2 on 2020-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seed/gallery'),
        ),
        migrations.AddField(
            model_name='species',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seed/gallery'),
        ),
    ]
