# Generated by Django 2.2 on 2020-03-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varietysupplier',
            name='documents',
            field=models.FileField(null=True, upload_to='seed/repo/supplier/document'),
        ),
        migrations.AlterField(
            model_name='varietysupplier',
            name='photo',
            field=models.ImageField(null=True, upload_to='seed/repo/supplier/image'),
        ),
    ]
