# Generated by Django 2.2 on 2020-03-31 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0003_auto_20200331_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarietyBaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(blank=True, choices=[('f', 'FRESH'), ('p', 'PROCESSING'), ('fp', 'FRESH/PROCESSING')], max_length=2, null=True)),
                ('ecology', models.CharField(blank=True, choices=[('AG', 'ACTIVE GREENHOUSE'), ('OF', 'OPEN FIELD'), ('OC', 'OUTDOORS, PROTECTED CULTURE'), ('PG', 'PASSIVE GREENHOUSE'), ('TE', 'TEMPERATE'), ('TR', 'TROPICAL')], max_length=2, null=True)),
                ('production_cycle', models.CharField(blank=True, choices=[('1', 'ACTIVE GREENHOUSE'), ('2', 'AUTUMN'), ('3', 'COOL'), ('4', 'COOL TO WARM'), ('5', 'EARLY'), ('6', 'FIRST EARLY'), ('7', 'LATE'), ('8', 'MAIN'), ('9', 'MEDIUM'), ('10', 'SECOND EARLY'), ('11', 'SPRING'), ('12', 'SPRING/AUTUMN'), ('13', 'SUMMER'), ('14', 'TROPICAL'), ('15', 'VERY LATE'), ('16', 'WARM'), ('17', 'WARM TO COOL'), ('18', 'WARM TO COOL TO WARM'), ('19', 'WINTER')], max_length=2, null=True)),
                ('color', models.CharField(blank=True, choices=[('1', 'BICOLOR'), ('2', 'BLACK'), ('3', 'DARK GREEN'), ('4', 'GREEN'), ('5', 'GREY'), ('6', 'LIGHT GREEN'), ('7', 'MEDIUM GREEN'), ('8', 'ORANGE'), ('9', 'PINK'), ('10', 'PURPLE'), ('11', 'RED'), ('12', 'WAX'), ('13', 'WHITE'), ('14', 'YELLOW')], max_length=2, null=True)),
                ('technical_description', models.CharField(blank=True, max_length=300, null=True)),
                ('Unique_selling_points_and_commercial_positioning', models.CharField(blank=True, max_length=100, null=True)),
                ('competition', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='seed/repo/Bancella/document')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.Variety')),
            ],
        ),
    ]
