# Generated by Django 3.0.5 on 2020-04-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0003_auto_20200422_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlifecycle',
            name='global_name',
        ),
        migrations.RemoveField(
            model_name='productlifecycle',
            name='other_global_name',
        ),
    ]
