# Generated by Django 3.0.5 on 2020-04-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0004_auto_20200422_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryplc',
            name='local_plc_date',
        ),
    ]
