# Generated by Django 2.2 on 2020-03-31 17:09

from django.db import migrations, models
import django.db.models.deletion
import seed.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200331_1008'),
        ('seed', '0005_auto_20200331_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLifeCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_name', models.CharField(max_length=50)),
                ('other_global_name', models.CharField(max_length=50)),
                ('global_plc', models.CharField(choices=[('0', 'Recorded'), ('1', 'Screening'), ('2', 'Development year 1'), ('3', 'Development year 2'), ('4', 'Pre-commercial'), ('5', 'Phase in'), ('6', 'Growth'), ('7', 'Cash'), ('8', 'Sell-out'), ('9', 'Phase out'), ('10', 'Obsolete')], max_length=2)),
                ('global_plc_date', models.DateField()),
                ('global_plc_remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='varietysupplier',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[seed.models.space_prohibited_validator]),
        ),
        migrations.CreateModel(
            name='CountryPLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(choices=[('0', 'Recorded'), ('1', 'Screening'), ('2', 'Development year 1'), ('3', 'Development year 2'), ('4', 'Pre-commercial'), ('5', 'Phase in'), ('6', 'Growth'), ('7', 'Cash'), ('8', 'Sell-out'), ('9', 'Phase out'), ('10', 'Obsolete')], max_length=2)),
                ('local_plc_date', models.DateField()),
                ('trial_and_development_results', models.CharField(blank=True, max_length=200, null=True)),
                ('go_to_market_approach', models.CharField(blank=True, max_length=200, null=True)),
                ('local_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('local_picture', models.FileField(upload_to='seed/repo/country_plc/document')),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.Contact')),
                ('person_in_charge_of_development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.Person')),
            ],
        ),
    ]
