# Generated by Django 3.0.5 on 2020-04-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0005_remove_countryplc_local_plc_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductLifeCycle',
            new_name='ProductLifeCycleLog',
        ),
    ]
