# Generated by Django 3.0.5 on 2020-04-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0006_auto_20200423_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPLCLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Recorded'), ('1', 'Screening'), ('2', 'Development year 1'), ('3', 'Development year 2'), ('4', 'Pre-commercial'), ('5', 'Phase in'), ('6', 'Growth'), ('7', 'Cash'), ('8', 'Sell-out'), ('9', 'Phase out'), ('10', 'Obsolete')], max_length=2)),
                ('country_plc_date', models.DateField(blank=True, null=True)),
                ('CountryPLC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.CountryPLC')),
            ],
        ),
    ]
