# Generated by Django 2.2 on 2020-03-31 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0006_auto_20200331_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryplc',
            name='global_plc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.ProductLifeCycle'),
        ),
    ]
