# Generated by Django 2.2 on 2020-04-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0007_countryplc_global_plc'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='product_life_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.ProductLifeCycle'),
        ),
    ]
