# Generated by Django 2.2 on 2020-04-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0008_species_product_life_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlifecycle',
            name='global_plc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productlifecycle',
            name='other_global_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
