# Generated by Django 3.0.5 on 2020-05-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0008_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryplc',
            name='global_plc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.Variety'),
        ),
    ]
