# Generated by Django 2.2 on 2020-04-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0009_auto_20200401_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='plc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seed.ProductLifeCycle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variety',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seed.ProductType'),
            preserve_default=False,
        ),
    ]
