# Generated by Django 2.2 on 2020-04-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0010_auto_20200402_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='ph',
            field=models.ImageField(blank=True, null=True, upload_to='seed/'),
        ),
        migrations.AlterField(
            model_name='species',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seed/repo/speices/image/'),
        ),
    ]
