# Generated by Django 3.0.5 on 2020-05-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0011_auto_20200508_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
    ]
