# Generated by Django 2.2 on 2020-04-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0011_auto_20200402_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='model2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.Model2'),
        ),
    ]
