# Generated by Django 3.0.5 on 2020-05-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0012_auto_20200514_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'permissions': (('group_level', 'Group level'),)},
        ),
    ]
