# Generated by Django 2.2 on 2020-04-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0012_auto_20200402_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varietybasedata',
            old_name='Unique_selling_points_and_commercial_positioning',
            new_name='unique_selling_points_and_commercial_positioning',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='ph',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
