# Generated by Django 3.0.5 on 2020-05-14 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seed', '0013_auto_20200514_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 14, 23, 7, 42, 151030)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variety',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variety',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
