# Generated by Django 2.2 on 2020-04-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0014_auto_20200403_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdivision',
            name='type',
        ),
        migrations.AlterField(
            model_name='variety',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.VarietySupplier'),
        ),
        migrations.AlterField(
            model_name='varietysupplier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
