# Generated by Django 2.2 on 2020-04-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0015_auto_20200406_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='supplier',
        ),
    ]
