# Generated by Django 3.0.5 on 2020-05-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0016_variety_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='country',
            field=models.ManyToManyField(null=True, to='seed.Country'),
        ),
    ]
