# Generated by Django 2.2 on 2020-04-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0016_remove_variety_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='global_crop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seed.GlobalCrop'),
            preserve_default=False,
        ),
    ]
