# Generated by Django 3.0.5 on 2020-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('seed', '0017_variety_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='country',
        ),
        migrations.AddField(
            model_name='variety',
            name='group',
            field=models.ManyToManyField(null=True, to='auth.Group'),
        ),
    ]
