# Generated by Django 2.2 on 2020-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0017_variety_global_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='variety_seed_type',
            field=models.CharField(choices=[('o', 'Open Pollinated'), ('h', 'Hybrid')], default='o', max_length=2),
            preserve_default=False,
        ),
    ]
