# Generated by Django 2.2 on 2020-04-06 13:50

from django.db import migrations, models
import seed.models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0018_variety_variety_seed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='variety_supplier_id',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[seed.models.space_prohibited_validator]),
        ),
        migrations.AddField(
            model_name='variety',
            name='variety_supplier_name',
            field=models.CharField(default='name-by-supplier', max_length=50),
            preserve_default=False,
        ),
    ]
