# Generated by Django 2.2 on 2020-04-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200331_1008'),
        ('seed', '0019_auto_20200406_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='supplier_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.Contact'),
            preserve_default=False,
        ),
    ]
