# Generated by Django 3.0.5 on 2020-05-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0020_auto_20200518_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='latin_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
