# Generated by Django 2.2 on 2020-04-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0020_variety_supplier_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='crop_family',
        ),
    ]
