# Generated by Django 3.0.5 on 2020-05-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('seed', '0021_auto_20200521_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
