# Generated by Django 2.2 on 2020-04-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0022_variety_crop_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='global_name',
        ),
    ]
