# Generated by Django 3.0.5 on 2020-05-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0022_auto_20200524_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=60)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.Species')),
            ],
        ),
    ]
