# Generated by Django 2.2 on 2020-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0023_remove_variety_global_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='global_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
