# Generated by Django 3.0.5 on 2020-05-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0023_customattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarietyAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=75)),
                ('custom_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.CustomAttribute')),
                ('variety', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.Variety')),
            ],
        ),
    ]
