# Generated by Django 3.0.5 on 2020-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0024_varietyattributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varietyattributevalue',
            name='value',
            field=models.CharField(max_length=150),
        ),
    ]
