# Generated by Django 2.2 on 2020-04-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0034_remove_variety_global_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='global_crop',
            field=models.ForeignKey(error_messages={'invalid': 'you custom error message'}, on_delete=django.db.models.deletion.CASCADE, to='seed.GlobalCrop'),
        ),
    ]
