# Generated by Django 2.2 on 2020-04-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0037_auto_20200413_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlifecycle',
            options={'ordering': ['global_plc_date']},
        ),
        migrations.RenameField(
            model_name='species',
            old_name='sow_KG_HA_max_interval1',
            new_name='sow_KG_HA_direct_max_interval',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='sow_KG_HA_min_interval1',
            new_name='sow_KG_HA_direct_min_interval',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='sow_transplant_max_interval',
            new_name='sow_KG_HA_transplant_max_interval',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='sow_transplant_min_interval',
            new_name='sow_KG_HA_transplant_min_interval',
        ),
        migrations.AlterField(
            model_name='species',
            name='sow_type',
            field=models.CharField(blank=True, choices=[('d', 'DIRECT SOWING'), ('t', 'TRANSPLANT'), ('b', 'Both')], default='b', max_length=1, null=True),
        ),
    ]
