# Generated by Django 2.2 on 2020-04-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0038_auto_20200413_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varietyimage',
            name='photo',
            field=models.ImageField(upload_to='seed/repo/variety/image'),
        ),
    ]
