# Generated by Django 2.2 on 2020-04-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0040_auto_20200414_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='CropFamily',
            new_name='crop_family',
        ),
    ]
