# Generated by Django 2.2 on 2020-03-31 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.Entity'),
            preserve_default=False,
        ),
    ]
